apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-standalone
  template:
    metadata:
      labels:
        app: redis-standalone
    spec:
      containers:
      - name: redis
        image: redis:6.0.16
        ports:
        - containerPort: 6379
        args: ["redis-server", "--requirepass", "C!tyt3ch@123", "--appendonly", "yes"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone
spec:
  ports:
  - port: 6379
  selector:
    app: redis-standalone

