apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: backup
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      name: console
    - port: 9000
      name: s3
  type: ClusterIP

