apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: backup
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - "minio"
            - "server"
            - "/data"
            - "--console-address"
            - ":9090"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /mnt/minio/data
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
      volumes:
        - name: data
          hostPath:
            path: /mnt/minio/data

