apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: backup
  labels:
    environment: production
    app: backup-app
type: Opaque
data:
  access-key: c3VzaGFudA==
  secret-key: MTIzNEFTREY=
